# Communication service configuration

version: "1.0.0"

service:
  host: "0.0.0.0"
  port: 8002
  log_level: "INFO"

communication:
  hardware:
    network:
      force_mock: true # Set to true only for testing without hardware
      plc:
        ip: "192.168.0.130"
        tag_file: "backend/resources/tags/MicroColdSpray_basic.csv"
      ssh:
        host: "192.168.0.200"
        port: 22
        username: "root"
        password: "deltatau"

  polling:
    interval: 0.2 # Tag polling interval in seconds
    batch_size: 50 # Number of tags to read in one batch

  services:
    tag_mapping:
      version: "1.0.0"
      config_file: "backend/config/tags.yaml"
    tag_cache:
      version: "1.0.0"
    motion:
      version: "1.0.0"
    equipment:
      version: "1.0.0"

  system_defaults:
    safety:
      safe_z: 40.0 # Safe Z height for motion (mm)

internal_states:
  rules:
    powder_feed_on:
      type: "comparison"
      tag: "feeders.feeder{1|2}.running"
      operator: "equal"
      value: true
      description: "Powder feed system is running"

    deagglomerator_on:
      type: "comparison"
      tag: "deagglomerators.deagg{1|2}.duty_cycle"
      operator: "less_than"
      value: 35
      description: "Deagglomerator is running (duty cycle < 35%)"

    flows_stable:
      type: "multi_condition"
      description: "Gas flows are stable"
      conditions:
      - tag: "gas_control.main_flow.measured"
        operator: "greater_than"
        value: 0.0
      - tag: "gas_control.feeder_flow.measured"
        operator: "greater_than"
        value: 0.0

    pressures_stable:
      type: "multi_condition"
      description: "System pressures are stable"
      conditions:
      - tag: "pressure.chamber"
        operator: "less_than"
        value: 5.0
      - tag: "pressure.main_supply"
        operator: "greater_than"
        value: 50.0

    at_valid_position:
      type: "multi_condition"
      description: "System is at a valid position"
      conditions:
      - tag: "motion.position.z"
        operator: "less_than_equal"
        value: "{safety.safe_z}"
      - tag: "motion.status.z"
        operator: "equal"
        value: 4

    at_trough_position:
      type: "multi_condition"
      description: "System is at trough position"
      conditions:
      - tag: "motion.position.x"
        operator: "equal"
        value: 0.0
      - tag: "motion.position.y"
        operator: "equal"
        value: 0.0
      - tag: "motion.position.z"
        operator: "equal"
        value: 0.0

    motion_enabled:
      type: "comparison"
      description: "Motion system is enabled and ready"
      tag: "motion.status.module"
      operator: "equal"
      value: true
