version: "1.0.0"
service:
  name: "data_collection"
  host: "0.0.0.0"
  port: 8004
  log_level: "INFO"
  history_retention_days: 30
components:
  database:
    version: "1.0.0"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "dbpassword"
    database: "postgres"
    pool:
      min_size: 2
      max_size: 10
      command_timeout: 60.0
