plc_tags:
  AMC.Ax1AxisStatus: 4
  AMC.Ax1Position: 0.0
  AMC.Ax2AxisStatus: 4
  AMC.Ax2Position: 0.0
  AMC.Ax3AxisStatus: 4
  AMC.Ax3Position: 10.0
  AMC.ModuleStatus: true
  AOS32-0.1.2.1: 2506
  AOS32-0.1.2.2: 2784
  AOS32-0.1.6.1: 35
  AOS32-0.1.6.2: 500
  AOS32-0.1.6.3: 35
  AOS32-0.1.6.4: 500
  BoosterPumpStart: false
  BoosterPumpStop: false
  ChamberPressure: 2.5
  FeederFlowRate: 5.0
  FeederPressure: 500.0
  FeederSwitch: true
  MainFlowRate: 50.0
  MainFlowStable: true
  MainGasPressure: 80.0
  MainSwitch: true
  MechPumpStart: false
  MechPumpStop: false
  MoveX: false
  MoveXY: false
  MoveY: false
  MoveZ: false
  NozzlePressure: 55.0
  NozzleSelect: false
  Open: true
  P10: false
  P106: 500
  P110: false
  P6: 500
  Partial: false
  RegulatorPressure: 60.0
  SetHome: false
  Shutter: false
  VentSwitch: false
  XAxis.Accel: 100.0
  XAxis.Complete: true
  XAxis.Decel: 100.0
  XAxis.InProgress: false
  XAxis.Velocity: 10.0
  XYMove.Complete: true
  XYMove.InProgress: false
  XYMove.LINRamps: 75
  XYMove.LINVelocity: 10.0
  XYMove.Status: 0
  XYMove.XPosition: 0.0
  XYMove.YPosition: 0.0
  YAxis.Accel: 100.0
  YAxis.Complete: true
  YAxis.Decel: 100.0
  YAxis.InProgress: false
  YAxis.Velocity: 10.0
  ZAxis.Accel: 50.0
  ZAxis.Complete: true
  ZAxis.Decel: 50.0
  ZAxis.InProgress: false
  ZAxis.Velocity: 5.0
version: 1.0.0
