version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend/config:/app/backend/config
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
    ports:
      - "8000-8004:8000-8004"
    environment:
      - PYTHONPATH=/app/backend/src
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    driver: bridge 